export function getLocalBusinessSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'ACME Sign & Graphics Co.',
    description:
      'Signage, LED displays, vehicle wraps, and custom apparel fabricated in-house for businesses across Atlantic Canada.',
    url: 'https://acmesign.ca',
    telephone: '+1-902-481-1007',
    email: 'acmesign01@gmail.com',
    address: {
      '@type': 'PostalAddress',
      streetAddress: '25 Raddall Avenue, Unit 4',
      addressLocality: 'Dartmouth',
      addressRegion: 'Nova Scotia',
      postalCode: 'B3B 1L4',
      addressCountry: 'CA',
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '08:30',
      closes: '17:00',
    },
    areaServed: [
      'Halifax',
      'Dartmouth',
      'Bedford',
      'Sackville',
      'Truro',
      'Wolfville',
      'Kentville',
      'Digby',
      'Yarmouth',
      'Pictou',
      'Antigonish',
      'New Glasgow',
      'Sydney',
      'Cape Breton',
      'Moncton',
      'Amherst',
      'New Brunswick',
      'Prince Edward Island',
    ],
  }
}
